# Generated by Django 3.1.3 on 2020-12-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tthapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clingredient',
            name='cost',
            field=models.CharField(max_length=200, verbose_name='Цена закупки'),
        ),
        migrations.AlterField(
            model_name='clmenupos',
            name='cost',
            field=models.IntegerField(max_length=200, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='clmenupos',
            name='img',
            field=models.CharField(blank=True, max_length=200, verbose_name='Картинка'),
        ),
    ]
