# Generated by Django 3.1.3 on 2020-12-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tthapp', '0002_auto_20201206_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clmenupos',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
