# Generated by Django 3.1.3 on 2020-12-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tthapp', '0003_auto_20201206_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clingredient',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='Цена закупки'),
        ),
    ]
